bugfix: do not mutate initialValue array on multiselect prompt
natemoo-re/clack pull request #64
Opened 2023-02-18 23:05 UTC by banjo

Fixed #63. The array passed into `initialValue` on the `multi-select` prompt is not cloned, so the original array is mutated if a value not selected in the array is selected.

You could use `structuredClone` for this, but it got support from Node 17+, which might not be ideal. I choose the JSON way because it has good support and is not a shallow clone. If I am not mistaken the array should only include strings which won't make it a problem.

2023-02-19 00:06 UTC, ulken requested changes
> You could use structuredClone for this, but it got support from Node 17+, which might not be ideal. I choose the JSON way because it has good support and is not a shallow clone. If I am not mistaken the array should only include strings which won't make it a problem.

I think we should strive to support the active LTS (18) and 16 reaches EOL later this year, so I think using `structuredClone` would be fine. With the library being so new and all, I would have a hard time understanding why anyone starting a new project would go for anything lower.

Right now, primitive values are supported, but that [might change](https://github.com/natemoo-re/clack/issues/44#issuecomment-1435779929), making the JSON parsing/serialization brittle.

For this particular case though, we would get away with a shallow clone, since it's a `push()` which mutates the array. But might not be desirable to prevent future mistakes.

Further more, looking at the implementation of `multiselect`, I've found some more oddities. E.g. for this particular case, I see no reason as to why we keep track of selected options. Just tracking the selected values would be enough. Especially since the UI code maps out the values of the selected options anyway, doing extra, unnecessary work.

I think it would be better to a complete overhaul of the component than to patch individual scratches. I'll have a go tomorrow and get back to you.

2023-02-19 09:47 UTC, ulken commented
@banjo if you're affected by this, could you do the job in user land and shallow clone the `initialValue` array until a proper fix lands?

```ts
{
  initialValue: [...initialValue]
}
```

2023-02-19 10:07 UTC, banjo commented
> @banjo if you're affected by this, could you do the job in user land and shallow clone the `initialValue` array until a proper fix lands?
> 
> ```ts
> {
>   initialValue: [...initialValue]
> }
> ```

Yeah, that's my current implementation so it's by no means a hurry for my sake.

2023-02-19 10:11 UTC, ulken commented
Splendid 👍 

Thanks for being patient and reporting the bug 🐛

2023-02-19 17:57 UTC, banjo commented
> Splendid 👍 
> 
> Thanks for being patient and reporting the bug 🐛 

No problem, impressive maintenance from your side. Great job!👌

2023-02-20 06:30 UTC, natemoo-re commented on packages/core/src/prompts/multi-select.ts
> +		this.selectedValues = JSON.parse(JSON.stringify(opts.initialValue)) || [];
Yep this seems reasonable to me!

2023-02-20 06:34 UTC, natemoo-re commented
Thanks for the PR and for the reviews! I think a shallow clone is okay in this situation, so I'd rather go with that for simplicity.

On mobile rn but will get this merged and released when I'm back at my computer!

2023-02-20 06:44 UTC, ulken commented
I have an upcoming PR with (IMO) several improvements (including fixing the issue above) to the implementation of this component. I've made the changes, just have to self-review and write the PR description. 

I'll open it within a few hours, if you want to hold off on merging this.

Of course fine to merge this separately, if you prefer.

2023-02-20 11:04 UTC, ulken commented
#65 ready for review.

2023-02-21 01:48 UTC, natemoo-re commented
Amazing thank you both! Closing this in favor of #65.

2023-02-21 01:48 UTC, closed without merging